openapi: 3.0.3
info:
  title: Bookstore API
  version: 1.0.0
  description: A sample REST API for managing books in a digital catalog.

servers:
  - url: https://api.example.com/v1

paths:
  /books:
    get:
      summary: Get all books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBook'
      responses:
        '201':
          description: Book created
        '400':
          description: Invalid input

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
          example: "abc123"
        title:
          type: string
        author:
          type: string
        publishedYear:
          type: integer
    NewBook:
      type: object
      required:
        - title
        - author
      properties:
        title:
          type: string
        author:
          type: string
        publishedYear:
          type: integer

security:
  - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

